INSERT INTO STUDENTS(name, group_id)
VALUES
    ('good', 4);

DELETE STUDENTS
WHERE ID >= 1;

SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS_LOGS;

CALL roll_back(TO_TIMESTAMP('2023/03/24 01:32:01', 'YYYY/MM/DD HH:MI:SS'));
